### PR TITLE
Spanish Colombia translation

### PR DESCRIPTION
**Pull request by marioy47**
Greetings,

This is the translation of your plugin to Spanish.  Hope it meets your standards.

### CODE REVIEW

**Comment by NateWr** [comment]
Thanks @marioy47!  There are a couple places [here](https://github.com/marioy47/business-profile/commit/96dbd740a096edc1821e23ab476e0c46814023fe#diff-1d1f9b1997489d5d5db9511d0347494eR237), [here](https://github.com/marioy47/business-profile/commit/96dbd740a096edc1821e23ab476e0c46814023fe#diff-1d1f9b1997489d5d5db9511d0347494eR240), [here](https://github.com/marioy47/business-profile/commit/96dbd740a096edc1821e23ab476e0c46814023fe#diff-1d1f9b1997489d5d5db9511d0347494eR244) and [here](https://github.com/marioy47/business-profile/commit/96dbd740a096edc1821e23ab476e0c46814023fe#diff-1d1f9b1997489d5d5db9511d0347494eR499) where separator spaces get dropped. Can you add them back in where appropriate?

I should probably fix the translation setup so that it's clearer what's being translated there, but for now just adding the spaces should solve the problem.

Thanks!

**Comment by marioy47** [comment]
@NateWr, Spaces added

**Comment by NateWr** [comment]
Perfect, thanks @marioy47!

**Comment by NateWr** [comment]
Hi @marioy47, I'm planning to release a small update to Business Profile next week. There are a few string changes for translation.

I've uploaded a new .pot file to master. If you have the time, I'd love to include an update to the Spanish translation with the update next week. Let me know if you have any questions.

**Pull request merged**
