### PR TITLE
Portuguese Translation

### PR DESCRIPTION
**Pull request by lmartins**

### CODE REVIEW

**Comment by NateWr** [comment]
Thanks @lmartins! There are a few places ([here](https://github.com/lmartins/business-profile/commit/ba707bb5ebaf5f1fa3a1f1418c0bd0b41630bc29#diff-d9ecbbcf5bcc78701d4327fc309dd165R236) [here](https://github.com/lmartins/business-profile/commit/ba707bb5ebaf5f1fa3a1f1418c0bd0b41630bc29#diff-d9ecbbcf5bcc78701d4327fc309dd165R239) and [here](https://github.com/lmartins/business-profile/commit/ba707bb5ebaf5f1fa3a1f1418c0bd0b41630bc29#diff-d9ecbbcf5bcc78701d4327fc309dd165R244)) where the original uses spaces on either side of the text but the translation doesn't use them. Can you add them back in where appropriate?

**Comment by lmartins** [comment]
Hi @NateWr , I've just reviewed all strings and pushed the update. Tried to submit a new PR but it seems it needs this one to be closed perhaps?

**Comment by NateWr** [comment]
Thanks @lmartins! Github pulls all your new commits in for me so it's already merged.

**Comment by NateWr** [comment]
Hi @lmartins, I'm planning to release a small update to Business Profile next week. It includes a couple of minor changes to translation strings.

If you have the time, I'd love to ship an updated Portugese translation with the new version. I've uploaded an up-to-date .pot file into the master branch if you want to take a look.

**Comment by lmartins** [comment]
Hi @NateWr , just submitted the PR.
Not really sure how to pull the changes from the main repo to the fork, so I had to delete my previous fork and do a new one.
Cheers.

**Comment by NateWr** [comment]
Thanks! Syncing a fork can seem tough at first but [this guide](https://help.github.com/articles/syncing-a-fork/) makes it pretty easy. Be sure to follow the "tip" at the top to configure a remote.

**Comment by lmartins** [comment]
Thanks for the tip Nate.

**Pull request merged**
