### PR TITLE
Added classes to page settings

### PR DESCRIPTION
**Pull request by lucspe**
These are rendered in the admin options page.

### CODE REVIEW

**Comment by NateWr** [comment]
Thanks for this @lucspe, but I actually need to manage the changes in the [original library](https://github.com/NateWr/simple-admin-pages), and do a versioned update on the library before implementing them here. The reason for that is because the library is loaded in separate versioned instances, to prevent conflicts between two plugins running different versions at the same time.

I'll try to make sure that's included with the next update. The issue to track is https://github.com/NateWr/business-profile/issues/66.

If you could remove hte updates to the files under `/lib/`, I'll leave this PR open so that it can be merged once the library is updated.

**Comment by lucspe** [comment]
The library file should be on par also on simple admin pages as that is the
same pull request file I sent you there and that you merged already.


2017-03-07 11:04 GMT+01:00 Nate Wright <notifications@github.com>:

**Comment by NateWr** [comment]
That's great. But the changes to those `lib` files need to come with a version update of the library, rather than just the one-off changes. This will include changes to class names and other things to manage the potential conflicts. I'll manage this on my end, if you can just remove the lib changes from this PR request.

**Comment by lucspe** [comment]
Ok, again as for previous change, I would need to ask you for you help.

What would be the best way to achieve that with github?

Sorry but my knowledge with github is relatively limited.


2017-03-07 11:11 GMT+01:00 Nate Wright <notifications@github.com>:

**Comment by NateWr** [comment]
Hi @lucspe, if you can just remove the changes you made to `lib/simple-admin-pages/classes/AdminPageSetting.class.php` in a subsequent commit, that should do the trick.

**Comment by lucspe** [comment]
I have done that. Hope it works OK now.

**Comment by NateWr** [comment]
Thanks @lucspe! I've merged that PR. I also prefixed the class names to prevent clashes from other styles that might be loaded in the admin: c074eb0bec56d4ac65a6fc422be828aec4c5c90e

Planning to put out an update today.

**Pull request merged**
