### PR TITLE
Sync Multiple locations With WPCS

### PR DESCRIPTION
**Pull request by robneu**
This pulls in changes in the master branch as well as the ones made in my WPCS branch (#19) . It also applies similar fixes to the new CPT class. Once these two branches are reviewed, finalized, and merged in, I'll continue working on building out the locations features.

### CODE REVIEW

**Comment by NateWr** [comment]
Amazing. Thanks for the code review/PR!

So, there are a number of code formatting issues which we discussed not doing. But then I looked back at [our previous conversation](https://github.com/NateWr/business-profile/issues/12#issuecomment-88402389) and I can see that I was completely and utterly unclear in my comment. It took me ages just to figure out what I was trying to say.

I wanted to keep much of the code formatting aligned with my other restaurant plugins. In retrospect, I think this plugin has much wider applicability and I'm happy to adopt a more generalized code format in the hopes it will encourage wider developer contribution.

So I'm inclined to take everything here as-is. However, there are just a couple of issues I'd like to address:

- What are the new dot files in assets? Are they part of a codesniffer package? Are they used along with a grunt config or some other tool? I've generally kept dev tools out of the repo but I'm happy to reconsider that if we want to implement a proper grunt toolchain of some kind.

- We need to preserve `bp_initilalize_map()` in the js code. That's the one thing I think is a real danger for backwards compatibility, because if the map's container changes width/height, the map needs to be re-initialized. So, for instance, one of my themes calls that funtion to reinitialize the map when a slide-out panel is shown/hidden. I suspect at least one person has done something similar. To preserve the code formatting, let's just add a wrapper function: `function bp_initialize_map() { bpInitializeMap(); }`.

- `assets/js/map.js:55` This comment was a general description of the file and is not really appropriate where it sits now. Can you either remove it or include it with the top comment on the file.

- What do you think about making `bpMaps` and `bpInfoWindows` global JS variables? I haven't really worked through it, but I'm thinking it might be useful to easily expose this data for manipulation on the client side, especially as we implement multiple locations. I'm tthinking easily being able to update the map, but maybe that's the wrong approach. Maybe for updating a map at run time the Google Maps API needs a different var exposed.

It seems to me that this PR includes the other, so when we're square on everything I can just merge this one, rather than merging the other than this one. Am I right on that?

**Comment by NateWr** [comment]
PS - Thanks for switching over to the singleton pattern while maintaining BC.

**Comment by robneu** [comment]
The dot files are read by [JSHint](http://jshint.com/), [JSCS](http://jscs.info/), and [esformatter](https://github.com/millermedeiros/esformatter). Those tools can be used as part of a grunt/gulp/whatever configuration, as part of someone's editor configuration, or just as CLI tools. 

The JSHint file is taken directly from WordPress core and the JSCS and esformatter files are set up to conform to WordPress/WordPress VIP JavaScipt coding standards. esformatter is a tool I've recently started using after Brady Vercher wrote a [plugin](https://github.com/cedaro/esformatter-wordpress) for it to automatically fix most JS issues using the WP coding standards. If you'd prefer to leave them out of the repo, I'll happily remove them.

That makes sense. I'll get that function switched back to the original format.

I'll switch that over to be a page level docblock.

JS is honestly my weakest area of development. I've only recently started to wrap my head around it a bit more, so I'm probably not the best person to answer that question. It sounds like exposing a global would be helpful, but I'm not sure whether or not it's the best way to go about it.

**Comment by robneu** [comment]
Oh, also, yes. If you'd prefer to just merge this one I can close the other and you can just hold off on merging anything into the master branch until we're done implementing everything on this one.

**Comment by NateWr** [comment]
Ok, let's keep the dot files for now. I don't have a good reason not to. Is the `assets` folder a common place for them to sit? Unless it's a pretty standard place for them, maybe we can move them to a `tools` folder? I'm used to just images, fonts, stylesheets and scripts sitting in the `assets` folder.

Let's not bother with the global variables in JS for now. It is easier to add them later than remove them once they've been added, and I'm not sure yet if they're the right place for it. I'd rather make them global once someone requests it.

So once we decide on the location of the dot files, I'm happy to merge this. I'll merge it into the `multiple-locations` branch. That way I can make maintenance releases on `master` if required. But I don't have any feature plans for that branch beyond multiple locations, so we won't need to worry about lots of duplicated work on `master` and `multiple-locations`.

Thanks again!

**Comment by robneu** [comment]
Sounds good. The way those configuration files work is they apply to the directory they live in and all nested directories within it. If you put them in the root, they apply to everything, etc. 

Moving them to a directory outside of `assets` would make them not function correctly. They could be moved directly to the `js` directory if you prefer though.

**Comment by NateWr** [comment]
Ok let's leave the dot files in place. It's late here so I don't want to start on the merge process but I'll try to get this merged tomorrow morning (UK time).

Thanks again!

**Comment by robneu** [comment]
Alrighty, sounds good man. Let me know if you find any other issues before you merge it!

**Pull request merged**
